### ISSUE TITLE
file name mistake?

### ISSUE THREAD

**Issue by jacobsayono** [bashbunni/dotfiles#7]
hi is there a reason why your file name in `dotfiles/.config/nvim/` is called `.init.cim` instead of `.init.vim`?

i am also having trouble running the :PlugInstall command in nvim (following your nvim setup tutorial on youtube)
i have already installed the plugin from
```
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```

there is a `plug.vim` in my `~/.local/share/nvim/site/autoload` directory

but i still can't run the :PlugInstall command ):

i don't seem to see a folder called `autoload` in your `.config/nvim/` folder
even thought you use the path `call plug#begin('~/.config/nvim/autoload/')` in your `.init.vim`

i also notice that when i run `vim` in terminal
it runs neovim v0.4
but i can also run 'nvim' in terminal
that runs neovim v0.9

both runs neovim (wth?)
![Screenshot from 2022-11-23 19-51-09](https://user-images.githubusercontent.com/46827431/203690144-36910948-6a14-4081-8694-2f61a9dd2e56.png)

here's `:checkhealth` for neovim v0.9
![Screenshot from 2022-11-23 19-54-35](https://user-images.githubusercontent.com/46827431/203690451-c37a5264-b64f-4189-aada-085c6aed8c41.png)

thank you so much for helping!

update: removed `vim` from `/usr/bin`
now i only have `nvim` from `/usr/local/bin`

i also tried deleting all nvim related files in root (and cloned repo), reinstalled:
![Screenshot from 2022-11-23 22-53-02](https://user-images.githubusercontent.com/46827431/203715111-9def5b9b-8f8d-42fb-877d-0dbf1ffa840b.png)

i didn't clone your .config file yet, and it seems like :PlugInstall won't run even though the plugin is still installed.

**Comment by Jay1** [comment]
Do you have an any error at all when you load nvim ?

**Comment by Zer0dev-byte** [comment]
It's because she uses neovim (I think)

**Comment by bashbunni** [comment]
oh HA that's the backup of my old vim config 😂 Now you only need the `init.lua` file. Sorry for the confusion
